//
// Created by Samuel Jones on 2/11/22.
//

#include "random.h"
#include "hardware/structs/rosc.h"
#include <string.h>


void random_insecure_bytes(uint8_t *bytes, size_t len) {
    memset(bytes, 0, len);
    for (size_t i=0; i<len; i++) {
        for (int j=0; j<8; j++) {
            bytes[i] |= (rosc_hw->randombit << j);
        }
    }
}

/*!
 *  @brief  Generate a psuedorandom 32 bit number using congruence
 *  
 *  @param  last    The previous number generated by this algorithm or the seed
 *  
 *  @return The next psuedorandom 32-bit number in the sequence
 * 
 *  This generator is a congruental generator of the form:
 *      
 *      m(i) = a * m(i-1) + c
 * 
 *  Using:
 *      
 *      a = 1812433253
 *      c = 1
 * 
 *  In the simulator this probably isn't different from just calling rand();
 */
uint32_t random_insecure_u32_congruence(uint32_t last)
{
    return last * 1812433253 + 1;
}
