//
// Created by Samuel Jones on 2/21/22.
//

#include "random.h"
#include <stdlib.h>
#include <time.h>
#include <stdbool.h>

static bool seeded = false;

void random_insecure_bytes(uint8_t *bytes, size_t len) {

    if (!seeded) {
        srand((unsigned) time(NULL));
        seeded = true;
    }
    for (size_t i=0; i<len; i++) {
        bytes[i] = rand() & 0xFF;
    }
}

/*!
 *  @brief  Generate a psuedorandom 32 bit number using congruence
 *  
 *  @param  last    The previous number generated by this algorithm or the seed
 *  
 *  @return The next psuedorandom 32-bit number in the sequence
 * 
 *  This generator is a congruental generator of the form:
 *      
 *      m(i) = a * m(i-1) + c
 * 
 *  Using:
 *      
 *      a = 1812433253
 *      c = 1
 * 
 *  In the simulator this probably isn't different from just calling rand();
 */
uint32_t random_insecure_u32_congruence(uint32_t last)
{
    return last * 1812433253 + 1;
}
