// ASSET HEADER AUTOMATICALLY GENERATED

// Included for struct asset
#include "assetList.h"

#ifndef _new_badge_monsters_assets_h_
#define _new_badge_monsters_assets_h_

extern const struct asset new_badge_monsters_assets_Access_Control_Alligator;
extern const struct asset new_badge_monsters_assets_Adware_Anteater;
extern const struct asset new_badge_monsters_assets_Backdoor_Bee;
extern const struct asset new_badge_monsters_assets_Botnet_Bat;
extern const struct asset new_badge_monsters_assets_Brute_Force_Baboon;
extern const struct asset new_badge_monsters_assets_Crypto_Raptor;
extern const struct asset new_badge_monsters_assets_DDOS_Dragon;
extern const struct asset new_badge_monsters_assets_DNS_Dolphin;
extern const struct asset new_badge_monsters_assets_Exploit_Eagle;
extern const struct asset new_badge_monsters_assets_Firewall_Flyer;
extern const struct asset new_badge_monsters_assets_Hacker_Hawk;
extern const struct asset new_badge_monsters_assets_IDS_Impalas;
extern const struct asset new_badge_monsters_assets_Intrusion_Detection_Iguana;
extern const struct asset new_badge_monsters_assets_Keylogger_Koala;
extern const struct asset new_badge_monsters_assets_Malware_Mantis;
extern const struct asset new_badge_monsters_assets_Packet_Sniffer_Puma;
extern const struct asset new_badge_monsters_assets_PenTest_Penguin;
extern const struct asset new_badge_monsters_assets_Phishing_Phoenix;
extern const struct asset new_badge_monsters_assets_Proxy_Porcupine;
extern const struct asset new_badge_monsters_assets_Ransomware_Rabbit;
extern const struct asset new_badge_monsters_assets_Rootkit_Rhino;
extern const struct asset new_badge_monsters_assets_SIEM_Sloth;
extern const struct asset new_badge_monsters_assets_SSL_Shark;
extern const struct asset new_badge_monsters_assets_Sniffer_Snail;
extern const struct asset new_badge_monsters_assets_Social_Engineer_Squirrel;
extern const struct asset new_badge_monsters_assets_Spam_Spider;
extern const struct asset new_badge_monsters_assets_Trojan_Turtle;
extern const struct asset new_badge_monsters_assets_Two_Factor_Tiger;
extern const struct asset new_badge_monsters_assets_VPN_Vulture;
extern const struct asset new_badge_monsters_assets_Worm_Wombat;

#endif /* _new_badge_monsters_assets_h_ */
