/* Begin code generated by png-to-badge-asset from slot-earth.png Sun Jun  2 08:32:08 2024. */
static const uint16_t slot_earth_colormap[15] = {
	0x0000, 0x2948, 0x7bd5, 0x8c54, 0x9cd9, 0x6b4f, 0xbddc, 0xa494, 0x424e, 0x5b11, 0x73d2, 0x9cd6,
	0xc5d9, 0x5b14, 0xdede,
}; /* 15 values */

static const uint8_t slot_earth_data[128] = {
	0, 0, 18, 50, 68, 33, 0, 0, 0, 5, 103, 115, 119, 34, 128, 0, 0, 39, 119, 117,
	53, 136, 41, 0, 9, 66, 58, 187, 57, 169, 34, 128, 18, 44, 188, 204, 59, 186, 66, 144,
	146, 147, 187, 204, 187, 136, 146, 33, 36, 58, 187, 202, 138, 168, 136, 40, 212, 50, 183, 117,
	136, 137, 136, 136, 221, 42, 151, 122, 136, 136, 56, 136, 36, 54, 35, 206, 235, 138, 138, 136,
	150, 188, 170, 206, 235, 59, 50, 129, 22, 75, 198, 236, 179, 91, 68, 144, 9, 70, 102, 102,
	187, 58, 41, 16, 0, 36, 102, 238, 230, 68, 40, 0, 0, 9, 70, 110, 230, 100, 128, 0,
	0, 0, 18, 68, 66, 145, 0, 0, 
}; /* 128 values */

static const struct asset2 slot_earth = {
	.type = PICTURE4BIT,
	.seqNum = 1,
	.x = 16,
	.y = 16,
	.colormap = (const uint16_t *) slot_earth_colormap,
	.pixel = (const unsigned char *) slot_earth_data,
};
/* End of code generated by png-to-badge-asset from slot-earth.png Sun Jun  2 08:32:08 2024 */
