/* Begin code generated by png-to-badge-asset from slot-planet.png Sun Jun  2 07:26:16 2024. */
static const uint16_t slot_planet_colormap[15] = {
	0x0000, 0xc50d, 0x20c1, 0x6286, 0x3143, 0xac8c, 0x51c2, 0x8305, 0xa3c7, 0x8bc9, 0xccc9, 0xd509,
	0x6243, 0x6a83, 0xe5ce,
}; /* 15 values */

static const uint8_t slot_planet_data[128] = {
	0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 35, 16, 0, 0, 0, 0,
	0, 2, 52, 80, 0, 0, 6, 120, 135, 101, 9, 144, 0, 0, 104, 171, 186, 140, 5, 0,
	0, 6, 122, 187, 187, 168, 16, 0, 0, 12, 219, 187, 187, 190, 128, 0, 0, 12, 120, 187,
	187, 235, 128, 0, 0, 6, 216, 187, 190, 187, 128, 0, 0, 6, 216, 187, 235, 186, 112, 0,
	0, 2, 215, 142, 187, 168, 96, 0, 0, 1, 45, 24, 138, 140, 0, 0, 2, 48, 1, 38,
	221, 96, 0, 0, 3, 73, 16, 0, 0, 0, 0, 0, 1, 25, 0, 0, 0, 0, 0, 0,
	16, 0, 0, 0, 0, 0, 0, 0, 
}; /* 128 values */

static const struct asset2 slot_planet = {
	.type = PICTURE4BIT,
	.seqNum = 1,
	.x = 16,
	.y = 16,
	.colormap = (const uint16_t *) slot_planet_colormap,
	.pixel = (const unsigned char *) slot_planet_data,
};
/* End of code generated by png-to-badge-asset from slot-planet.png Sun Jun  2 07:26:16 2024 */
