/* Begin code generated by png-to-badge-asset from slot-none.png Sun Jun  2 12:16:11 2024. */
static const uint16_t slot_none_colormap[1] = {
	0x0801,
}; /* 1 values */

static const uint8_t slot_none_data[128] = {
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 
}; /* 128 values */

static const struct asset2 slot_none = {
	.type = PICTURE4BIT,
	.seqNum = 1,
	.x = 16,
	.y = 16,
	.colormap = (const uint16_t *) slot_none_colormap,
	.pixel = (const unsigned char *) slot_none_data,
};
/* End of code generated by png-to-badge-asset from slot-none.png Sun Jun  2 12:16:11 2024 */
