/* Begin code generated by png-to-badge-asset from slot-galaxy.png Sun Jun  2 07:33:32 2024. */
static const uint16_t slot_galaxy_colormap[15] = {
	0x0841, 0x18c3, 0x4a4a, 0x2905, 0x20c2, 0x39c8, 0x5acc, 0x3186, 0x62cb, 0x5248, 0x7b8f, 0x940e,
	0xa4d2, 0xc594, 0xee98,
}; /* 15 values */

static const uint8_t slot_galaxy_data[128] = {
	0, 0, 18, 35, 20, 16, 0, 0, 0, 0, 86, 51, 68, 17, 4, 0, 0, 7, 34, 53,
	117, 35, 49, 20, 0, 8, 147, 88, 138, 102, 37, 17, 0, 24, 149, 136, 136, 147, 102, 48,
	0, 70, 137, 171, 202, 133, 54, 33, 0, 73, 172, 189, 220, 169, 115, 83, 0, 73, 171, 206,
	237, 200, 131, 51, 0, 69, 106, 205, 221, 200, 130, 113, 113, 19, 106, 139, 187, 202, 150, 49,
	118, 23, 38, 138, 171, 165, 150, 113, 50, 49, 114, 106, 168, 151, 38, 113, 2, 82, 49, 82,
	103, 53, 98, 113, 0, 18, 34, 34, 36, 50, 39, 51, 0, 1, 55, 85, 55, 118, 51, 113,
	0, 0, 1, 19, 119, 119, 83, 48, 
}; /* 128 values */

static const struct asset2 slot_galaxy = {
	.type = PICTURE4BIT,
	.seqNum = 1,
	.x = 16,
	.y = 16,
	.colormap = (const uint16_t *) slot_galaxy_colormap,
	.pixel = (const unsigned char *) slot_galaxy_data,
};
/* End of code generated by png-to-badge-asset from slot-galaxy.png Sun Jun  2 07:33:32 2024 */
