/* Begin code generated by png-to-badge-asset from slot-star.png Sun Jun  2 07:42:32 2024. */
static const uint16_t slot_star_colormap[15] = {
	0x1041, 0x0841, 0x18c4, 0x2103, 0x39c7, 0x528c, 0x2988, 0x6c14, 0x29cb, 0x42cf, 0x1906, 0x7c12,
	0xb598, 0xdf1d, 0x83cf,
}; /* 15 values */

static const uint8_t slot_star_data[128] = {
	0, 0, 17, 2, 0, 16, 0, 16, 0, 1, 0, 3, 0, 0, 0, 17, 0, 17, 0, 4,
	0, 0, 0, 1, 17, 16, 0, 37, 34, 0, 1, 1, 16, 0, 2, 103, 134, 34, 0, 0,
	16, 1, 38, 151, 152, 162, 0, 0, 16, 3, 89, 188, 181, 150, 0, 1, 3, 68, 87, 205,
	203, 149, 67, 0, 3, 68, 155, 205, 203, 149, 67, 32, 0, 2, 133, 236, 181, 98, 1, 17,
	0, 2, 136, 151, 150, 162, 17, 17, 0, 2, 168, 151, 138, 162, 17, 17, 17, 1, 42, 105,
	162, 33, 17, 17, 17, 17, 18, 37, 17, 17, 17, 17, 17, 17, 17, 4, 1, 16, 17, 17,
	17, 16, 0, 3, 1, 16, 1, 17, 
}; /* 128 values */

static const struct asset2 slot_star = {
	.type = PICTURE4BIT,
	.seqNum = 1,
	.x = 16,
	.y = 16,
	.colormap = (const uint16_t *) slot_star_colormap,
	.pixel = (const unsigned char *) slot_star_data,
};
/* End of code generated by png-to-badge-asset from slot-star.png Sun Jun  2 07:42:32 2024 */
