/* Begin code generated by png-to-badge-asset from slot-astronaut.png Sun Jun  2 07:54:32 2024. */
static const uint16_t slot_astronaut_colormap[15] = {
	0x0800, 0x1882, 0x41c7, 0xce59, 0xe71b, 0xbdd7, 0x6b4d, 0x18c3, 0x7bcf, 0xef5c, 0xd6da, 0x5acb,
	0xad55, 0xf7de, 0x94d2,
}; /* 15 values */

static const uint8_t slot_astronaut_data[128] = {
	0, 0, 18, 51, 69, 97, 0, 0, 0, 0, 5, 0, 112, 64, 0, 0, 0, 0, 115, 0,
	128, 144, 0, 0, 0, 1, 106, 0, 0, 75, 0, 0, 0, 3, 85, 149, 197, 221, 0, 0,
	0, 195, 132, 169, 157, 221, 64, 0, 0, 158, 6, 173, 212, 92, 94, 0, 14, 152, 0, 93,
	157, 33, 52, 0, 3, 160, 0, 61, 221, 0, 205, 0, 5, 176, 14, 157, 221, 144, 228, 0,
	5, 0, 5, 221, 157, 208, 5, 0, 7, 0, 5, 208, 4, 144, 1, 0, 0, 0, 12, 64,
	5, 144, 0, 0, 0, 0, 5, 144, 3, 64, 0, 0, 0, 0, 93, 208, 3, 208, 0, 0,
	0, 0, 221, 208, 5, 147, 0, 0, 
}; /* 128 values */

static const struct asset2 slot_astronaut = {
	.type = PICTURE4BIT,
	.seqNum = 1,
	.x = 16,
	.y = 16,
	.colormap = (const uint16_t *) slot_astronaut_colormap,
	.pixel = (const unsigned char *) slot_astronaut_data,
};
/* End of code generated by png-to-badge-asset from slot-astronaut.png Sun Jun  2 07:54:32 2024 */
