/* Begin code generated by png-to-badge-asset from slot-rocket.png Sun Jun  2 07:05:43 2024. */
static const uint16_t slot_rocket_colormap[15] = {
	0x0000, 0x630c, 0xb596, 0xce58, 0xdedb, 0xad54, 0x31c6, 0xc800, 0xe000, 0x9281, 0xe4c0, 0xd145,
	0x7a41, 0xbb42, 0x61c1,
}; /* 15 values */

static const uint8_t slot_rocket_data[128] = {
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 32, 0, 0, 0, 0,
	0, 0, 52, 16, 0, 0, 0, 0, 0, 3, 53, 0, 0, 0, 0, 0, 3, 51, 80, 0,
	0, 0, 0, 0, 67, 67, 96, 0, 0, 0, 0, 3, 52, 69, 0, 0, 0, 0, 7, 132,
	67, 80, 0, 0, 0, 7, 136, 68, 53, 0, 0, 0, 0, 0, 131, 69, 128, 0, 0, 0,
	0, 0, 19, 88, 112, 0, 0, 0, 0, 9, 169, 184, 0, 0, 0, 0, 0, 202, 144, 7,
	0, 0, 0, 0, 12, 222, 0, 0, 0, 0, 0, 0, 13, 224, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 
}; /* 128 values */

static const struct asset2 slot_rocket = {
	.type = PICTURE4BIT,
	.seqNum = 1,
	.x = 16,
	.y = 16,
	.colormap = (const uint16_t *) slot_rocket_colormap,
	.pixel = (const unsigned char *) slot_rocket_data,
};
/* End of code generated by png-to-badge-asset from slot-rocket.png Sun Jun  2 07:05:43 2024 */
