/* Begin code generated by png-to-badge-asset from slot-comet.png Sun Jun  2 08:22:33 2024. */
static const uint16_t slot_comet_colormap[15] = {
	0x0000, 0x0001, 0x0005, 0x0006, 0x0048, 0x00ca, 0x014c, 0x0003, 0x01cf, 0x0a51, 0x2ad3, 0x4bd6,
	0x7c98, 0x9d9a, 0xd6dd,
}; /* 15 values */

static const uint8_t slot_comet_data[128] = {
	1, 16, 16, 17, 35, 69, 85, 84, 0, 1, 17, 18, 69, 86, 101, 67, 17, 1, 23, 36,
	102, 102, 101, 99, 0, 17, 36, 86, 136, 136, 100, 66, 1, 23, 70, 136, 153, 136, 84, 39,
	17, 19, 105, 154, 169, 134, 68, 39, 17, 38, 154, 170, 169, 133, 67, 119, 23, 89, 171, 186,
	169, 101, 66, 113, 19, 155, 187, 186, 168, 100, 55, 17, 117, 188, 204, 186, 168, 83, 33, 18,
	120, 205, 220, 186, 166, 50, 17, 17, 121, 222, 220, 185, 100, 113, 16, 17, 21, 205, 203, 166,
	87, 17, 17, 1, 23, 106, 169, 83, 113, 17, 17, 17, 17, 119, 34, 33, 17, 17, 17, 16,
	17, 17, 17, 113, 17, 1, 17, 17, 
}; /* 128 values */

static const struct asset2 slot_comet = {
	.type = PICTURE4BIT,
	.seqNum = 1,
	.x = 16,
	.y = 16,
	.colormap = (const uint16_t *) slot_comet_colormap,
	.pixel = (const unsigned char *) slot_comet_data,
};
/* End of code generated by png-to-badge-asset from slot-comet.png Sun Jun  2 08:22:33 2024 */
