/* This program converts x11 color definitions to badge colors */

#include <stdio.h>
#include <stdlib.h>
#include <errno.h>
#include <string.h>

static void fixup_color_name(char *name)
{
	for (int i = 0; name[i]; i++)
		if (name[i] == ' ')
			name[i] = '_';
}

static void print_high_binary_digits(int num_digits, unsigned char value)
{
	for (int i = 0; i < num_digits; i++)
		printf("%1d", !!(value & (1 << (7 - i))));
}

static void print_color(char *name, unsigned char r, unsigned char g, unsigned char b)
{
	printf("#define x11_%s 0b", name);
	print_high_binary_digits(5, r);
	print_high_binary_digits(6, g);
	print_high_binary_digits(5, b);
	printf("\n");
}

int main(__attribute__((unused)) int argc, __attribute__((unused)) char *argv[])
{
	FILE *f;
	char *l, line[1024], color_name[1024];
	unsigned char r, g, b;
	int rc;

	printf("#ifndef X11_COLORS__\n");
	printf("#define X11_COLORS__\n");
	printf("/* This code is generated by tools/x11-colors-to-badge-colors.\n");
	printf(" * Do not edit this code.\n");
	printf(" */\n");
	f = fopen("/etc/X11/rgb.txt", "r");
	if (!f) {
		fprintf(stderr, "Failed to open /etc/X11/rgb.txt: %s\n", strerror(errno));
		exit(1);
	}

	do {
		l = fgets(line, sizeof(line), f);
		if (!l)
			break;
		memset(color_name, 0, sizeof(color_name));
		rc = sscanf(line, "%hhu %hhu %hhu %[^\n]%*c", &r, &g, &b, color_name);
		if (rc != 4)
			continue;
		fixup_color_name(color_name);
		print_color(color_name, r, g, b);
	} while (1);
	fclose(f);
	printf("#endif\n");
	return 0;
}

