
all: build-docs

build-docs:
	bash ./scripts/build_badgeappdev_docs.sh

serve-docs:
	bash ./scripts/serve_badgeappdev_docs.sh

build-user-docs:
	bash ./scripts/build_user_docs.sh

serve-user-docs:
	bash ./scripts/serve_user_docs.sh

clean:
	rm -rf .bin
	rm -rf .dist
